"""add language to posts

Revision ID: 896599e14b85
Revises: a49e5409b701
Create Date: 2025-12-10 13:44:34.174872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896599e14b85'
down_revision = 'a49e5409b701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
