"""Complete database schema with all tables

Revision ID: 2bf5e0358901
Revises: 
Create Date: 2025-10-06 12:26:13.437579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf5e0358901'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_person', sa.String(length=64), nullable=False),
    sa.Column('customer_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('billing_address', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('relationship_status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_company_name'), ['company_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_customer_number'), ['customer_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_updated_at'), ['updated_at'], unique=False)

    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_name'), ['name'], unique=True)

    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_permission'), ['permission'], unique=True)

    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_title'), ['title'], unique=True)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('vehicle_type', sa.String(length=64), nullable=True),
    sa.Column('fuel_type', sa.String(length=32), nullable=True),
    sa.Column('capacity', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('last_service_date', sa.DateTime(), nullable=True),
    sa.Column('next_service_date', sa.DateTime(), nullable=True),
    sa.Column('insurance_expiry', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_vehicle_number'), ['vehicle_number'], unique=True)

    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('activity_status', sa.String(length=64), nullable=True),
    sa.Column('availability_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('approval_status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_last_login'), ['last_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('payment_terms', sa.String(length=128), nullable=True),
    sa.Column('date_scheduled', sa.DateTime(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('time_allocated', sa.Integer(), nullable=True),
    sa.Column('contact_person', sa.String(length=128), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('job_number', sa.String(length=20), nullable=True),
    sa.Column('stores_confirmation', sa.Boolean(), nullable=True),
    sa.Column('work_done', sa.Boolean(), nullable=True),
    sa.Column('technical_manager_approval', sa.Boolean(), nullable=True),
    sa.Column('accounts_payment', sa.Boolean(), nullable=True),
    sa.Column('invoice_number', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('stores_confirmation_by_id', sa.Integer(), nullable=True),
    sa.Column('work_done_by_id', sa.Integer(), nullable=True),
    sa.Column('technical_manager_approval_by_id', sa.Integer(), nullable=True),
    sa.Column('accounts_payment_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accounts_payment_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['stores_confirmation_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['technical_manager_approval_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.ForeignKeyConstraint(['work_done_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_accounts_payment'), ['accounts_payment'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_accounts_payment_by_id'), ['accounts_payment_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_date_completed'), ['date_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_date_scheduled'), ['date_scheduled'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_job_number'), ['job_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_stores_confirmation'), ['stores_confirmation'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_stores_confirmation_by_id'), ['stores_confirmation_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_technical_manager_approval'), ['technical_manager_approval'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_technical_manager_approval_by_id'), ['technical_manager_approval_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_work_done'), ['work_done'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_work_done_by_id'), ['work_done_by_id'], unique=False)

    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('allowances_worth', sa.Float(), nullable=True),
    sa.Column('deductions_worth', sa.Float(), nullable=True),
    sa.Column('bank_name', sa.String(length=64), nullable=True),
    sa.Column('bank_account_number', sa.String(length=64), nullable=True),
    sa.Column('bank_account_type', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_number')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_hire_date'), ['hire_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_staff_number'), ['staff_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_user_id'), ['user_id'], unique=True)

    op.create_table('job_assistant',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_assistant')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_user_id'))
        batch_op.drop_index(batch_op.f('ix_staff_staff_number'))
        batch_op.drop_index(batch_op.f('ix_staff_position_id'))
        batch_op.drop_index(batch_op.f('ix_staff_phone'))
        batch_op.drop_index(batch_op.f('ix_staff_last_updated'))
        batch_op.drop_index(batch_op.f('ix_staff_hire_date'))
        batch_op.drop_index(batch_op.f('ix_staff_email'))
        batch_op.drop_index(batch_op.f('ix_staff_department_id'))
        batch_op.drop_index(batch_op.f('ix_staff_date_created'))

    op.drop_table('staff')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_work_done_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_work_done'))
        batch_op.drop_index(batch_op.f('ix_job_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_job_updated_at'))
        batch_op.drop_index(batch_op.f('ix_job_title'))
        batch_op.drop_index(batch_op.f('ix_job_technical_manager_approval_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_technical_manager_approval'))
        batch_op.drop_index(batch_op.f('ix_job_stores_confirmation_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_stores_confirmation'))
        batch_op.drop_index(batch_op.f('ix_job_job_number'))
        batch_op.drop_index(batch_op.f('ix_job_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_job_date_scheduled'))
        batch_op.drop_index(batch_op.f('ix_job_date_completed'))
        batch_op.drop_index(batch_op.f('ix_job_customer_id'))
        batch_op.drop_index(batch_op.f('ix_job_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_created_at'))
        batch_op.drop_index(batch_op.f('ix_job_assigned_to_id'))
        batch_op.drop_index(batch_op.f('ix_job_accounts_payment_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_accounts_payment'))

    op.drop_table('job')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_last_seen'))
        batch_op.drop_index(batch_op.f('ix_user_last_login'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    op.drop_table('role_permission')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_vehicle_number'))
        batch_op.drop_index(batch_op.f('ix_vehicle_updated_at'))
        batch_op.drop_index(batch_op.f('ix_vehicle_created_at'))

    op.drop_table('vehicle')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    op.drop_table('role')
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_title'))

    op.drop_table('position')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_permission'))

    op.drop_table('permission')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_name'))

    op.drop_table('department')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_updated_at'))
        batch_op.drop_index(batch_op.f('ix_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_index(batch_op.f('ix_customer_customer_number'))
        batch_op.drop_index(batch_op.f('ix_customer_created_at'))
        batch_op.drop_index(batch_op.f('ix_customer_company_name'))

    op.drop_table('customer')
    # ### end Alembic commands ###
