"""Recreate job table with new columns

Revision ID: a41a04675466
Revises: dc7345cce292
Create Date: 2025-09-30 13:04:24.221691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41a04675466'
down_revision = 'dc7345cce292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('payment_terms', sa.String(length=128), nullable=True),
    sa.Column('date_scheduled', sa.DateTime(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('job_number', sa.String(length=20), nullable=True),
    sa.Column('stores_confirmation', sa.Boolean(), nullable=True),
    sa.Column('work_done', sa.Boolean(), nullable=True),
    sa.Column('technical_manager_approval', sa.Boolean(), nullable=True),
    sa.Column('accounts_payment', sa.Boolean(), nullable=True),
    sa.Column('invoice_number', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('stores_confirmation_by_id', sa.Integer(), nullable=True),
    sa.Column('work_done_by_id', sa.Integer(), nullable=True),
    sa.Column('technical_manager_approval_by_id', sa.Integer(), nullable=True),
    sa.Column('accounts_payment_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accounts_payment_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['stores_confirmation_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['technical_manager_approval_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_done_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_accounts_payment'), ['accounts_payment'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_accounts_payment_by_id'), ['accounts_payment_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_date_completed'), ['date_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_date_scheduled'), ['date_scheduled'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_job_number'), ['job_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_stores_confirmation'), ['stores_confirmation'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_stores_confirmation_by_id'), ['stores_confirmation_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_technical_manager_approval'), ['technical_manager_approval'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_technical_manager_approval_by_id'), ['technical_manager_approval_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_work_done'), ['work_done'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_work_done_by_id'), ['work_done_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_work_done_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_work_done'))
        batch_op.drop_index(batch_op.f('ix_job_updated_at'))
        batch_op.drop_index(batch_op.f('ix_job_title'))
        batch_op.drop_index(batch_op.f('ix_job_technical_manager_approval_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_technical_manager_approval'))
        batch_op.drop_index(batch_op.f('ix_job_stores_confirmation_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_stores_confirmation'))
        batch_op.drop_index(batch_op.f('ix_job_job_number'))
        batch_op.drop_index(batch_op.f('ix_job_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_job_date_scheduled'))
        batch_op.drop_index(batch_op.f('ix_job_date_completed'))
        batch_op.drop_index(batch_op.f('ix_job_customer_id'))
        batch_op.drop_index(batch_op.f('ix_job_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_created_at'))
        batch_op.drop_index(batch_op.f('ix_job_assigned_to_id'))
        batch_op.drop_index(batch_op.f('ix_job_accounts_payment_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_accounts_payment'))

    op.drop_table('job')
    # ### end Alembic commands ###
