"""Current database state

Revision ID: dc7345cce292
Revises: 
Create Date: 2025-09-30 12:59:55.228612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7345cce292'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stores_confirmation_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('work_done_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('technical_manager_approval_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accounts_payment_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('job_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_job_accounts_payment'), ['accounts_payment'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_accounts_payment_by_id'), ['accounts_payment_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_stores_confirmation'), ['stores_confirmation'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_stores_confirmation_by_id'), ['stores_confirmation_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_technical_manager_approval'), ['technical_manager_approval'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_technical_manager_approval_by_id'), ['technical_manager_approval_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_work_done'), ['work_done'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_work_done_by_id'), ['work_done_by_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['accounts_payment_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['technical_manager_approval_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['work_done_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['stores_confirmation_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_job_work_done_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_work_done'))
        batch_op.drop_index(batch_op.f('ix_job_technical_manager_approval_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_technical_manager_approval'))
        batch_op.drop_index(batch_op.f('ix_job_stores_confirmation_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_stores_confirmation'))
        batch_op.drop_index(batch_op.f('ix_job_accounts_payment_by_id'))
        batch_op.drop_index(batch_op.f('ix_job_accounts_payment'))
        batch_op.alter_column('job_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('accounts_payment_by_id')
        batch_op.drop_column('technical_manager_approval_by_id')
        batch_op.drop_column('work_done_by_id')
        batch_op.drop_column('stores_confirmation_by_id')

    # ### end Alembic commands ###
